### ISSUE TITLE
Issue with installing pepsickle

### ISSUE THREAD

**Issue by Ahmedalaraby20** [pdxgx/pepsickle#2] opened 2023-06-04 14:00 UTC
I keep running into this error while running `conda env create --file pepsickle_conda_build.yml`

```
Retrieving notices: ...working... done
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - liblapack==3.9.0=16_osx64_openblas
  - llvm-openmp==15.0.6=h61d9ccf_0
  - python==3.8.15=hf9b03c3_0_cpython
  - ncurses==6.3=h96cf925_1
  - libcxx==14.0.6=hccf4f1f_0
  - tk==8.6.12=h5dbffcc_0
  - openssl==3.0.7=hfd90126_1
  - libsqlite==3.40.0=ha978bb4_0
  - ca-certificates==2022.12.7=h033912b_0
  - xz==5.2.6=h775f41a_0
  - scipy==1.9.3=py38hfb8b963_2
  - numpy==1.24.0=py38hc2f29e8_0
  - libblas==3.9.0=16_osx64_openblas
  - libgfortran5==11.3.0=h082f757_27
  - scikit-learn==1.2.0=py38h573ff9c_0
  - libffi==3.4.2=h0d85af4_5
  - libopenblas==0.3.21=openmp_h429af6e_3
  - bzip2==1.0.8=h0d85af4_4
  - libzlib==1.2.13=hfd90126_4
  - libcblas==3.9.0=16_osx64_openblas
  - libgfortran==5.0.0=11_3_0_h97931a8_27
  - readline==8.1.2=h3899abd_0

```

Same error on 2 different systems

**Comment by weederb23** [comment] 2023-06-08 17:15
Hi @Ahmedalaraby20 can you give me a few details about what systems you tested this on? Specifically what operating system each is running on would be helpful in narrowing down what the issue is. 

Thanks!

**Comment by weederb23** [comment] 2023-06-12 18:08
It would also help to know what version of conda you're using.

**Comment by Ahmedalaraby20** [comment] 2023-06-13 05:58
Hi @weederb23 , 
I could only reproduce this issue when trying to install pepsickle from git but when using `pip install pepsickle` it worked well, 
I am running Ubuntu 22.04 conda 3.10, cuda 11.8 and

**Comment by weederb23** [comment] 2023-06-13 15:47
Hi @Ahmedalaraby20, 

Thanks for the info! I'm glad you were able to get it running via the other install method. I'll look into this a bit further to see if I can figure out the issue installing directly from git so that both methods work as intended. If you have any other issues while running pepsickle just let me know and I'll see if I can help you solve them!

**Comment by weederb23** [comment] 2023-06-23 16:12
It looks like this issue is an issue resulting from an older conda version that doesn't include the required package versions. This should be resolved by updating conda itself.

**Closed as completed by weederb23** 2023-06-23 16:12 UTC
