### ISSUE TITLE
Retrain models in updated scikit-learn version

### ISSUE THREAD

**Issue by jaimicore** [pdxgx/pepsickle#1] opened 2022-12-19 09:03 UTC
Hi pepsickle team,

I would like to use pepsickle with the in-vitro model using the following command:

`pepsickle -f sequences.faa -p I -m in-vitro `

But each time I use this parameters, independently of the sequence, I have the following error:

`AttributeError: 'GradientBoostingClassifier' object has no attribute '_loss' `

Searching on internet I found that this may occur because the model was trained in an older version of scikit-learn (0.23.3), currently I am using (1.2.0). when changing to  the  v0.23.3 it works, but this is not optimal.

Would it be possible to re-train the models in an updated scikit-learn versions ?

Great tool, I am quite happy how easy is to install, use and it is super fast.

**Comment by weederb23** [comment] 2022-12-21 19:14
Hi @jaimicore,

You are correct. The main issue stems from differences in scikit-learn versioning. By design sklearn doesn't build in reverse compatibility for models trained in previous versions. After some discussion, we think it does make sense to upgrade the current models trained in v0.23.3 using the newest stable release (v1.2.0) as this will make pepsickle dependent on a non-dev version of sklearn. 

Unfortunately, this is kind of a "one time" fix since the same compatibility concerns will likely arise with new releases of sklearn. For people who run into this issue in the future, we also plan to add a .yaml file for easy conda environment setup containing the appropriate versions of sklearn and other dependencies. 

It may take a few days to retrain the models (especially with the holidays), but we'll get to this ASAP.

**Comment by jaimicore** [comment] 2022-12-21 20:10
Thank you so much and no hurries. 

I am able to run *pepsickle* but I guess this fix could be useful for other users too.

**Comment by weederb23** [comment] 2022-12-26 21:16
@jaimicore models have been updated, and should work for scikit-learn v1.2.0

A .yml file has now been provided for installation through conda along with installation instructions in the README which should avoid this issue for future users.

Let me know if you run into any issues with the new release, if so I'll investigate further!

**Comment by weederb23** [comment] 2022-12-29 18:24
Closing issue.

**Closed as completed** 2022-12-29 18:24 UTC
Labels: bug

**Comment by jaimicore** [comment] 2023-01-02 10:33
All the combination of models and proteasomse work well. 
Thanks you so much.
